import path from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import importPlugin from "eslint-plugin-import";
import jsdoc from "eslint-plugin-jsdoc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
	baseDirectory: __dirname,
	recommendedConfig: js.configs.recommended,
	allConfig: js.configs.all,
});

const namingConventionClassFieldSelector = ["classicAccessor", "autoAccessor", "classMethod", "classProperty"];

export default [
	{
		ignores: [
			"**/*.js",
			"**/*.d.ts",
			"**/*.mjs",
			"**/*.cjs",
			"dist/**",
			"node_modules/**",
			"scripts/**",
			"drizzle.config.ts",
			"tests/**",
			"**/*.test.ts",
			"src/db/schema/**/*.ts",
		],
	},
	...compat.extends("eslint:recommended", "plugin:@typescript-eslint/recommended"),
	{
		plugins: {
			"@typescript-eslint": typescriptEslint,
			import: importPlugin,
		},
		settings: {
			"import/resolver": {
				node: {
					extensions: [".ts"],
				},
			},
			"import/cache": {
				lifetime: "Infinity",
			},
		},
		languageOptions: {
			parser: tsParser,
			ecmaVersion: "latest",
			sourceType: "commonjs",
			parserOptions: {
				project: "./tsconfig.json",
			},
		},
		rules: {
			"prefer-arrow-callback": ["error", { allowNamedFunctions: false, allowUnboundThis: false }],
			"object-shorthand": ["error", "never"],
			"max-params": ["error", 6],
			"max-depth": ["error", 6],
			"no-unused-vars": "off",
			"@typescript-eslint/no-unused-vars": [
				"error",
				{
					args: "none",
					caughtErrors: "none",
					destructuredArrayIgnorePattern: "^_",
					ignoreRestSiblings: true,
				},
			],
			"@typescript-eslint/no-unsafe-function-type": "off",
			"@typescript-eslint/no-empty-object-type": "off",
			"@typescript-eslint/no-wrapper-object-types": "off",
			"@typescript-eslint/consistent-type-imports": ["error", { "fixStyle": "separate-type-imports", "disallowTypeAnnotations": false }],
			"@typescript-eslint/restrict-plus-operands": "error",
			"@typescript-eslint/no-namespace": "off",
			"@typescript-eslint/ban-types": "off",
			curly: "error",
			"array-callback-return": "error",
			"no-constant-binary-expression": "error",
			"no-constructor-return": "error",
			"no-new-native-nonconstructor": "error",
			"no-self-compare": "error",
			"no-template-curly-in-string": "error",
			"no-unmodified-loop-condition": "error",
			camelcase: [
				"error",
				{
					properties: "always",
					allow: [
						"^_?tmp.*",
						"^_temp.*",
						"^m_.*",
						"^duration_ms$",
						"^cost_usd$",
						"^num_turns$",
						"^per_page$",
						"^page_size$",
						"^page_token$",
						// Drizzle DB schema columns (snake_case)
						"^team_id$", "^user_id$", "^organization_id$", "^model_id$",
						"^api_key$", "^key_alias$", "^key_name$", "^tpm_limit$", "^rpm_limit$",
						"^max_budget$", "^budget_id$", "^budget_reset_at$",
						"^model_spend$", "^model_max_budget$", "^max_tokens$", "^max_completion_tokens$",
						"^finish_reason$", "^allowed_routes$", "^tool_choice$", "^tool_calls$",
						"^stop_reason$", "^stop_sequences$",
						"^api_base$", "^request_id$", "^call_type$", "^model_group$", "^model_name$",
						"^model_info$", "^custom_llm_provider$", "^cache_control$",
						"^output_format$", "^output_config$", "^budget_tokens$",
						"^end_user_id$", "^object_permission_id$", "^access_group_ids$",
						"^created_at$", "^updated_at$", "^created_by$", "^updated_by$",
						"^successful_requests$", "^failed_requests$", "^api_requests$",
						"^mcp_namespaced_tool_name$", "^proxy_server_request$",
						"^request_tags$", "^requester_ip_address$",
						"^cache_read_input_tokens$", "^cache_creation_input_tokens$",
						"^cache_creation_token_details$", "^completion_tokens_details$", "^prompt_tokens_details$",
						"^soft_budget_cooldown$", "^max_parallel_requests$",
						"^budget_duration$", "^request_duration_ms$",
						"^rotation_count$", "^auto_rotate$", "^rotation_interval$",
						"^last_rotation_at$", "^key_rotation_at$", "^last_active$",
						"^team_alias$", "^user_alias$", "^organization_alias$", "^project_alias$",
						"^user_email$", "^user_role$", "^sso_user_id$",
						"^litellm_params$", "^model_aliases$",
						"^credential_name$", "^credential_values$", "^credential_info$",
						"^guardrail_name$", "^guardrail_info$",
						"^prompt_id$", "^prompt_info$",
						"^policy_name$", "^version_number$", "^version_status$", "^parent_version_id$",
						"^guardrails_add$", "^guardrails_remove$",
						"^search_tool_name$", "^search_tool_info$",
						"^unified_file_id$", "^unified_object_id$", "^model_object_id$", "^unified_resource_id$",
						"^index_name$", "^index_info$",
						"^access_group_name$", "^agent_name$", "^agent_card_params$",
						"^server_name$", "^mcp_access_groups$",
						"^tool_name$", "^tool_type$", "^input_policy$", "^output_policy$",
						"^skill_id$", "^display_title$", "^latest_version$",
						"^cronjob_id$", "^health_check_id$",
						"^param_name$", "^param_value$", "^config_type$", "^config_value$",
						"^cache_settings$", "^ui_settings$", "^sso_settings$",
						"^web_search_options$", "^context_management$", "^extra_headers$", "^parallel_tool_calls$",
						"^input_tokens$", "^output_tokens$", "^prompt_tokens$", "^completion_tokens$", "^total_tokens$",
						"^allowed_cache_controls$", "^allowed_model_region$", "^default_model$",
						"^exception_type$", "^exception_string$", "^status_code$", "^litellm_model_name$",
						// LiteLLM_* / liteLLM_* table names from Drizzle schemas
						"^LiteLLM_", "^liteLLM_",
						"^thinking_blocks$", "^reasoning_content$", "^input_schema$", "^tool_use_id$", "^tool_use$",
						"^soft_budget$", "^owned_by$", "^output_cost_per_token$", "^json_mode$",
						"^media_type$", "^disable_parallel_tool_use$", "^user_location$", "^max_uses$",
						"^supported_text$", "^reasoning_tokens$", "^text_tokens$", "^cached_tokens$", "^cache_creation_tokens$",
						"^hate_threatening$", "^harassment_threatening$", "^category_scores$",
						"^total_spend$", "^total_prompt_tokens$", "^total_completion_tokens$",
						"^input_cost_per_token$", "^max_retries$", "^stream_timeout$", "^extra_body$",
						"^max_input_tokens$", "^max_output_tokens$", "^supports_function_calling$",
						"^supports_parallel_function_calling$", "^supports_vision$", "^supports_system_messages$",
						"^supports_tool_choice$", "^litellm_provider$",
						"^allowed_fails$", "^cooldown_time$", "^num_retries$", "^max_fallbacks$", "^routing_strategy$",
						"^model_group_alias$", "^enable_pre_call_checks$", "^search_tools$", "^redis_url$", "^request_timeout$",
						"^master_key$", "^store_model_in_db$", "^websearch_override_target_model$",
						"^skip_provider_token_counting$", "^database_url$", "^database_connection_pool_limit$",
						"^proxy_logging_retry_min_delay$", "^max_log_files$",
						"^model_list$", "^litellm_settings$", "^router_settings$", "^general_settings$",
						"^end_turn$", "^web_search$", "^tool_call_id$", "^top_p$",
						"^anthropic_version$", "^content_block$", "^provider_specific_fields$",
						"^_hidden_params$",
						// Anthropic API response 字段（snake_case，非 TS 可控）
						"^container_content$", "^code_interpreter_results$",
						"^web_search_requests$", "^tool_search_requests$", "^inference_geo$",
						"^defer_loading$", "^allowed_callers$", "^input_examples$",
						// Anthropic streaming / responses API snake_case fields
						"^compaction_blocks$", "^web_search_results$", "^tool_results$",
						"^display_number$", "^container_id$",
					],
				},
			],
			"rest-spread-spacing": "error",
			"object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
			"no-trailing-spaces": "error",
			"no-multiple-empty-lines": "error",
			"no-multi-spaces": "error",
				"lines-between-class-members": [
					"error",
					{
						enforce: [
							{ blankLine: "always", prev: "method", next: "method" },
							{ blankLine: "always", prev: "method", next: "field" },
						],
					},
				],
			"default-case": "error",
			"default-case-last": "error",
			"grouped-accessor-pairs": "error",
			"no-alert": "error",
			"no-caller": "error",
			"no-confusing-arrow": "error",
			"no-div-regex": "error",
			"no-extend-native": "error",
			"no-sequences": "error",
			"no-var": "error",
			"prefer-const": "error",
			"prefer-exponentiation-operator": "error",
			"prefer-rest-params": "error",
			yoda: "error",
			"@typescript-eslint/prefer-regexp-exec": "error",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/no-unused-expressions": "error",
			"no-mixed-spaces-and-tabs": "off",
			"no-inner-declarations": "off",
			"no-prototype-builtins": "error",
			"@typescript-eslint/no-explicit-any": "error",
			"@typescript-eslint/naming-convention": [
				"error",
				{
					selector: "classProperty",
					modifiers: ["static", "readonly"],
					format: ["UPPER_CASE"],
					leadingUnderscore: "forbid",
				},
				{
					selector: namingConventionClassFieldSelector,
					modifiers: ["private"],
					format: ["camelCase"],
					leadingUnderscore: "require",
				},
				{
					selector: "parameterProperty",
					modifiers: ["private"],
					format: ["camelCase"],
					leadingUnderscore: "require",
				},
				{
					selector: ["classMethod", "classProperty"],
					modifiers: ["public"],
					format: ["camelCase", "PascalCase"],
					leadingUnderscore: "allow",
				},
				{
					selector: namingConventionClassFieldSelector,
					modifiers: ["public"],
					format: ["camelCase", "UPPER_CASE", "PascalCase"],
					leadingUnderscore: "forbid",
				},
				{
					selector: ["typeAlias", "interface", "enum", "class"],
					format: null,
					modifiers: ["exported"],
					custom: {
						regex: "^[A-Z][0-9A-Za-z_]*$",
						match: true,
					},
				},
			],
			"no-restricted-syntax": [
				"error",
				{
					selector: "ExportNamedDeclaration[source]",
					message: "禁止使用桶导出 (re-export)，请直接从源文件导入",
				},
				{
					selector: "ExportAllDeclaration",
					message: "禁止使用 export * 桶导出，请直接从源文件导入",
				},
			],
		},
	},
	{
		plugins: {
			jsdoc,
		},
		files: ["src/**/*.ts"],
		rules: {
			"jsdoc/require-jsdoc": [
				"error",
				{
					contexts: [
						"TSInterfaceDeclaration",
						"TSMethodSignature",
						"TSPropertySignature",
						"TSEnumDeclaration",
						"TSEnumMember",
						"TSTypeAliasDeclaration",
					],
					publicOnly: true,
					require: {
						ArrowFunctionExpression: true,
						ClassDeclaration: true,
						ClassExpression: true,
						FunctionDeclaration: true,
						FunctionExpression: true,
						MethodDefinition: true,
					},
					checkConstructors: false,
				},
			],
			"jsdoc/check-access": "error",
			"jsdoc/check-alignment": "error",
			"jsdoc/check-line-alignment": "error",
			"jsdoc/check-param-names": ["error", { checkDestructured: false }],
			"jsdoc/check-template-names": "error",
			"jsdoc/check-property-names": "error",
			"jsdoc/check-syntax": "error",
			"jsdoc/check-tag-names": "error",
			"jsdoc/check-types": "error",
			"jsdoc/check-values": "error",
			"jsdoc/empty-tags": "error",
			"jsdoc/implements-on-classes": "error",
			"jsdoc/match-description": ["off",
				"error",
				{
					matchDescription: "^[一-龥A-Za-z`\\d_]+[\\s\\S]*$",
					message: "描述必须以有效字符开头",
				},
			],
			"jsdoc/multiline-blocks": "error",
			"jsdoc/no-bad-blocks": "error",
			"jsdoc/no-blank-block-descriptions": "error",
			"jsdoc/no-defaults": "error",
			"jsdoc/require-asterisk-prefix": "error",
			"jsdoc/no-multi-asterisks": "error",
			"jsdoc/no-undefined-types": "error",
			"jsdoc/require-description": "off",
			"jsdoc/require-hyphen-before-param-description": "error",
			"jsdoc/require-param": ["error", { unnamedRootBase: ["arg"], checkDestructured: false }],
			"jsdoc/require-param-description": "off",
			"jsdoc/require-param-name": ["error"],
			"jsdoc/require-property": "error",
			"jsdoc/require-property-description": "error",
			"jsdoc/require-property-name": "error",
			"jsdoc/require-property-type": "error",
			"jsdoc/require-returns": "off",
			"jsdoc/require-returns-check": "error",
			"jsdoc/require-returns-description": "error",
			"jsdoc/require-template": "error",
			"jsdoc/require-throws": "error",
			"jsdoc/require-yields": "error",
			"jsdoc/require-yields-check": "error",
			"jsdoc/sort-tags": "error",
			"jsdoc/tag-lines": "error",
			"jsdoc/valid-types": "error",
		},
	},
];
